ARG UBUNTU_DIST=noble
FROM ubuntu:$UBUNTU_DIST

ARG UBUNTU_DIST
ARG SUPERFILE_VERSION
ARG BUILD_VERSION
ARG FULL_VERSION
ARG ARCH
ARG SPF_RELEASE

RUN mkdir -p /output/usr/bin
RUN mkdir -p /output/usr/share/doc/superfile
RUN mkdir -p /output/DEBIAN

# Upstream ships a single binary called "spf"; the project is named superfile
# but the command is not.
COPY ${SPF_RELEASE}/spf /output/usr/bin/spf
RUN chmod 755 /output/usr/bin/spf
COPY output/DEBIAN/control /output/DEBIAN/
COPY output/DEBIAN/postinst /output/DEBIAN/postinst
RUN chmod 755 /output/DEBIAN/postinst
COPY output/copyright /output/usr/share/doc/superfile/
COPY output/changelog.Debian /output/usr/share/doc/superfile/
COPY output/README.md /output/usr/share/doc/superfile/
RUN chmod 644 /output/usr/share/doc/superfile/*

RUN sed -i "s/DIST/$UBUNTU_DIST/" /output/usr/share/doc/superfile/changelog.Debian
RUN sed -i "s/FULL_VERSION/$FULL_VERSION/" /output/usr/share/doc/superfile/changelog.Debian
RUN sed -i "s/DIST/$UBUNTU_DIST/" /output/DEBIAN/control
RUN sed -i "s/SUPERFILE_VERSION/$SUPERFILE_VERSION/" /output/DEBIAN/control
RUN sed -i "s/BUILD_VERSION/$BUILD_VERSION/" /output/DEBIAN/control
RUN sed -i "s/SUPPORTED_ARCHITECTURES/$ARCH/" /output/DEBIAN/control

RUN dpkg-deb --build /output /superfile_${FULL_VERSION}.deb
